### ISSUE TITLE
Bug in login_test

### ISSUE THREAD

**Issue by GiuseppeGambardella** [benedettoscala/CiviConnect#24]
https://github.com/benedettoscala/CiviConnect/blob/479733d30d52b31772075d538b7cafeb399ea8ce/src/test/login_test.dart#L185

## EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK
The following NoSuchMethodError was thrown running a test:
The method 'call' was called on null.
Receiver: null
Tried calling: call()

### ✅ Probable Fix:
__home: LoginUtenteGUI(controller: controller ?? FakeUserManagementController()))__

**Comment by Type-Here** [comment]
No bug was there but changes made for log out test to work needed updates in login test  as well. Since it was your branch to work the issue will be closed. 
Anyway Fixed
